testName: MRT TEST

language : en
testIterations : 6
testItemNumber : 2
trapQuestions : 1
trialIterations: 3
trialItemNumber: 1
trialCondition: condition1
trialAudioDirectory: /static/speechFiles/MRT

conditions:
  - condition1
  - condition2

answer_dir : Results_MRT/

consent_info : |
  <p>With your consent, you agree to participate in the study “Modified Rhyme Test”.</p>
  <p>I agree that you may, for the purpose of carrying out, evaluating and presenting the above study, collect the following personal data from me </p>
  <ul>
    <li>Name</li>
    <li>Age</li>
    <li>Gender</li>
    <li>Nationality</li>
  </ul>

break: False

MRT:
  wordItemDirectory : RhymeTest_webApp/static/mrt_wrdlst_example.txt
  audioDirectory:
    - /static/speechFiles/MRT
    - /static/speechFiles/MRT

  instructions:
    - Once you play the audio, please listen to it till the end! You will not be given a second chance to listen.
    - Select the word that was played after you listen to it.
    - Once you select the word, you will be given the next set of words and the next audio clip.


